/**
 * ItalianPP API
 * ItalianPP API documentation
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The ProcurementDTO model module.
* @module model/ProcurementDTO
* @version 0.0.1
*/
export default class ProcurementDTO {
    /**
    * Constructs a new <code>ProcurementDTO</code>.
    * @alias module:model/ProcurementDTO
    * @class
    * @param code {String} 
    * @param contractorEopooCode {String} 
    * @param description {String} 
    * @param ippModalityCode {String} 
    * @param ippProcedureCode {String} 
    * @param ippSectorCode {String} 
    * @param totalAmount {Number} 
    */

    constructor(code, contractorEopooCode, description, ippModalityCode, ippProcedureCode, ippSectorCode, totalAmount) {
        
        
        this['code'] = code;
        this['contractorEopooCode'] = contractorEopooCode;
        this['description'] = description;
        this['ippModalityCode'] = ippModalityCode;
        this['ippProcedureCode'] = ippProcedureCode;
        this['ippSectorCode'] = ippSectorCode;
        this['totalAmount'] = totalAmount;
        
    }

    /**
    * Constructs a <code>ProcurementDTO</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/ProcurementDTO} obj Optional instance to populate.
    * @return {module:model/ProcurementDTO} The populated <code>ProcurementDTO</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ProcurementDTO();
                        
            
            if (data.hasOwnProperty('code')) {
                obj['code'] = ApiClient.convertToType(data['code'], 'String');
            }
            if (data.hasOwnProperty('contractorEopooCode')) {
                obj['contractorEopooCode'] = ApiClient.convertToType(data['contractorEopooCode'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('ippModalityCode')) {
                obj['ippModalityCode'] = ApiClient.convertToType(data['ippModalityCode'], 'String');
            }
            if (data.hasOwnProperty('ippProcedureCode')) {
                obj['ippProcedureCode'] = ApiClient.convertToType(data['ippProcedureCode'], 'String');
            }
            if (data.hasOwnProperty('ippSectorCode')) {
                obj['ippSectorCode'] = ApiClient.convertToType(data['ippSectorCode'], 'String');
            }
            if (data.hasOwnProperty('ref')) {
                obj['ref'] = ApiClient.convertToType(data['ref'], 'String');
            }
            if (data.hasOwnProperty('totalAmount')) {
                obj['totalAmount'] = ApiClient.convertToType(data['totalAmount'], 'Number');
            }
        }
        return obj;
    }

    /**
    * @member {String} code
    */
    code = undefined;
    /**
    * @member {String} contractorEopooCode
    */
    contractorEopooCode = undefined;
    /**
    * @member {String} description
    */
    description = undefined;
    /**
    * @member {Number} id
    */
    id = undefined;
    /**
    * @member {String} ippModalityCode
    */
    ippModalityCode = undefined;
    /**
    * @member {String} ippProcedureCode
    */
    ippProcedureCode = undefined;
    /**
    * @member {String} ippSectorCode
    */
    ippSectorCode = undefined;
    /**
    * @member {String} ref
    */
    ref = undefined;
    /**
    * @member {Number} totalAmount
    */
    totalAmount = undefined;




}
