/**
 * ItalianPP API
 * ItalianPP API documentation
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ItalianPpApi);
  }
}(this, function(expect, ItalianPpApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ItalianPpApi.ProcurementDTO();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ProcurementDTO', function() {
    it('should create an instance of ProcurementDTO', function() {
      // uncomment below and update the code to test ProcurementDTO
      //var instane = new ItalianPpApi.ProcurementDTO();
      //expect(instance).to.be.a(ItalianPpApi.ProcurementDTO);
    });

    it('should have the property code (base name: "code")', function() {
      // uncomment below and update the code to test the property code
      //var instane = new ItalianPpApi.ProcurementDTO();
      //expect(instance).to.be();
    });

    it('should have the property contractorEopooCode (base name: "contractorEopooCode")', function() {
      // uncomment below and update the code to test the property contractorEopooCode
      //var instane = new ItalianPpApi.ProcurementDTO();
      //expect(instance).to.be();
    });

    it('should have the property description (base name: "description")', function() {
      // uncomment below and update the code to test the property description
      //var instane = new ItalianPpApi.ProcurementDTO();
      //expect(instance).to.be();
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instane = new ItalianPpApi.ProcurementDTO();
      //expect(instance).to.be();
    });

    it('should have the property ippModalityCode (base name: "ippModalityCode")', function() {
      // uncomment below and update the code to test the property ippModalityCode
      //var instane = new ItalianPpApi.ProcurementDTO();
      //expect(instance).to.be();
    });

    it('should have the property ippProcedureCode (base name: "ippProcedureCode")', function() {
      // uncomment below and update the code to test the property ippProcedureCode
      //var instane = new ItalianPpApi.ProcurementDTO();
      //expect(instance).to.be();
    });

    it('should have the property ippSectorCode (base name: "ippSectorCode")', function() {
      // uncomment below and update the code to test the property ippSectorCode
      //var instane = new ItalianPpApi.ProcurementDTO();
      //expect(instance).to.be();
    });

    it('should have the property ref (base name: "ref")', function() {
      // uncomment below and update the code to test the property ref
      //var instane = new ItalianPpApi.ProcurementDTO();
      //expect(instance).to.be();
    });

    it('should have the property totalAmount (base name: "totalAmount")', function() {
      // uncomment below and update the code to test the property totalAmount
      //var instane = new ItalianPpApi.ProcurementDTO();
      //expect(instance).to.be();
    });

  });

}));
