/**
 * ItalianPP API
 * ItalianPP API documentation
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from './ApiClient';
import ProcurementDTO from './model/ProcurementDTO';
import ProcurementLotDTO from './model/ProcurementLotDTO';
import ProcurementLotResourceApi from './api/ProcurementLotResourceApi';
import ProcurementResourceApi from './api/ProcurementResourceApi';

/**
* ItalianPP_API_documentation.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var ItalianPpApi = require('index'); // See note below*.
* var xxxSvc = new ItalianPpApi.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new ItalianPpApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new ItalianPpApi.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new ItalianPpApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 0.0.1
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The ProcurementDTO model constructor.
     * @property {module:model/ProcurementDTO}
     */
    ProcurementDTO,

    /**
     * The ProcurementLotDTO model constructor.
     * @property {module:model/ProcurementLotDTO}
     */
    ProcurementLotDTO,

    /**
    * The ProcurementLotResourceApi service constructor.
    * @property {module:api/ProcurementLotResourceApi}
    */
    ProcurementLotResourceApi,

    /**
    * The ProcurementResourceApi service constructor.
    * @property {module:api/ProcurementResourceApi}
    */
    ProcurementResourceApi
};
