/**
 * ItalianPP API
 * ItalianPP API documentation
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ItalianPpApi);
  }
}(this, function(expect, ItalianPpApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ItalianPpApi.ProcurementResourceApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ProcurementResourceApi', function() {
    describe('countProcurementsUsingGET', function() {
      it('should call countProcurementsUsingGET successfully', function(done) {
        //uncomment below and update the code to test countProcurementsUsingGET
        //instance.countProcurementsUsingGET(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('createProcurementUsingPOST', function() {
      it('should call createProcurementUsingPOST successfully', function(done) {
        //uncomment below and update the code to test createProcurementUsingPOST
        //instance.createProcurementUsingPOST(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteProcurementUsingDELETE', function() {
      it('should call deleteProcurementUsingDELETE successfully', function(done) {
        //uncomment below and update the code to test deleteProcurementUsingDELETE
        //instance.deleteProcurementUsingDELETE(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getAllProcurementsUsingGET', function() {
      it('should call getAllProcurementsUsingGET successfully', function(done) {
        //uncomment below and update the code to test getAllProcurementsUsingGET
        //instance.getAllProcurementsUsingGET(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getProcurementUsingGET', function() {
      it('should call getProcurementUsingGET successfully', function(done) {
        //uncomment below and update the code to test getProcurementUsingGET
        //instance.getProcurementUsingGET(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateProcurementUsingPUT', function() {
      it('should call updateProcurementUsingPUT successfully', function(done) {
        //uncomment below and update the code to test updateProcurementUsingPUT
        //instance.updateProcurementUsingPUT(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
